name: Build PyP

on:
  push:
    branches:
      - patched

jobs:
  build:
    name: Build PyP
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: 3.8

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4
        with:
            poetry-version: 1.1.4

      - name: Build
        uses: poetry build

      - uses: actions/upload-artifact@v2
        with:
          name: Upload build
          path: dist/
