name: Generate OAS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: 3.8

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v2
        with:
            poetry-version: 1.0.9
      
      - name: Generate and patch
        run: make setup

      - name: Stub
        run: make m.pre-stub

      - name: Check lint errors
        run: poetry run pylint -E src
      
      - name: Run pytest
        run: poetry run pytest src
      
      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v3
        with:
            base: patched
