name: Generate OAS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check lock file
        run: poetry lock --check
      
      - name: Generate and patch
        run: make setup

      - name: Stub
        run: make m.pre-stub

      - name: Run pylint
        run: poetry run pylint -E src

      - name: Run mypy
        run: poetry run mypy src
      
      - name: Run pytest
        run: poetry run pytest src
      
      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v3
        with:
            base: patched
